Exercise from Think Stats, 2nd Edition (thinkstats2.com)<br>
Allen Downey

In [1]:
import nsfg
df = nsfg.ReadFemPreg()
df

,caseid,pregordr,howpreg_n,howpreg_p,moscurrp,nowprgdk,pregend1,pregend2,nbrnaliv,multbrth,...,laborfor_i,religion_i,metro_i,basewgt,adj_mod_basewgt,finalwgt,secu_p,sest,cmintvw,totalwgt_lb
0,1,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,8.8125
1,1,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,7.8750
2,2,1,NaN,NaN,NaN,NaN,5.0,NaN,3.0,5.0,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,9.1250
3,2,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,7.0000
4,2,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,6.1875
5,6,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4870.926435,5325.196999,8874.440799,1,23,NaN,8.5625
6,6,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4870.926435,5325.196999,8874.440799,1,23,NaN,9.5625
7,6,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4870.926435,5325.196999,8874.440799,1,23,NaN,8.3750
8,7,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,3409.579565,3787.539000,6911.879921,2,14,NaN,7.5625
9,7,2,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,3409.579565,3787.539000,6911.879921,2,14,NaN,6.6250
10,12,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,3612.781968,4146.013572,6909.331618,1,31,NaN,7.8125
11,14,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.069494,2810.302771,3039.904507,2,56,NaN,7.0000
12,14,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.069494,2810.302771,3039.904507,2,56,NaN,4.0000
13,14,3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,2418.069494,2810.302771,3039.904507,2,56,NaN,NaN
14,15,1,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,1667.816099,3200.862017,5553.495599,1,33,NaN,NaN
15,15,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,1667.816099,3200.862017,5553.495599,1,33,NaN,7.6875
16,15,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,1667.816099,3200.862017,5553.495599,1,33,NaN,7.5000
17,18,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,2957.257457,3404.403067,4153.371741,2,14,NaN,6.3125
18,18,2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,2957.257457,3404.403067,4153.371741,2,14,NaN,NaN
19,21,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3408.342437,3965.763949,7237.122630,1,48,NaN,8.7500
20,21,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3408.342437,3965.763949,7237.122630,1,48,NaN,8.1875
21,23,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,6210.373020,8120.841310,13533.382043,2,64,NaN,5.5625
22,23,2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,6210.373020,8120.841310,13533.382043,2,64,NaN,NaN
23,24,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.573258,4068.628645,7424.840414,1,27,NaN,6.7500
24,24,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.573258,4068.628645,7424.840414,1,27,NaN,7.3750
25,24,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.573258,4068.628645,7424.840414,1,27,NaN,6.8125
26,28,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3407.794208,3808.343516,6949.846082,2,57,NaN,8.1250
27,31,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3405.679025,4272.084519,5211.943113,1,2,NaN,7.1250
28,31,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3405.679025,4272.084519,5211.943113,1,2,NaN,6.0625
29,31,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3405.679025,4272.084519,5211.943113,1,2,NaN,7.4375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13563,12547,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3453.545517,6628.022524,11499.619080,1,52,NaN,7.6875
13564,12547,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3453.545517,6628.022524,11499.619080,1,52,NaN,7.6250
13565,12550,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3080.452699,3745.326058,5268.550165,1,79,NaN,8.1250
13566,12551,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,2418.538866,3653.453268,3951.940400,2,75,NaN,7.5000
13567,12554,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,1914.676604,2177.957240,2764.045534,2,75,NaN,NaN
13568,12554,2,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,0,0,0,1914.676604,2177.957240,2764.045534,2,75,NaN,NaN
13569,12556,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,5.8125
13570,12556,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,6.6875
13571,12556,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,6.0000
13572,12556,4,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,5.8125
13573,12561,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.089703,2698.650781,4497.301527,1,10,NaN,6.5625
13574,12561,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.089703,2698.650781,4497.301527,1,10,NaN,6.1250
13575,12564,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,1820.850938,2129.214067,2768.191208,2,44,NaN,NaN
13576,12565,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3195.641221,3834.241709,6652.409365,1,78,NaN,6.4375
13577,12565,2,35.0,1.0,8.0,NaN,NaN,NaN,NaN,NaN,...,0,0,0,3195.641221,3834.241709,6652.409365,1,78,NaN,NaN
13578,12566,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2080.317155,2422.820274,2627.548587,2,2,NaN,6.0000
13579,12566,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2080.317155,2422.820274,2627.548587,2,2,NaN,7.0000
13580,12568,1,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,2734.687353,4258.980140,7772.212858,2,28,NaN,NaN
13581,12568,2,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,2734.687353,4258.980140,7772.212858,2,28,NaN,6.3750
13582,12568,3,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,0,0,0,2734.687353,4258.980140,7772.212858,2,28,NaN,NaN
13583,12569,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,2580.967613,2925.167116,5075.164946,2,61,NaN,NaN
13584,12569,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2580.967613,2925.167116,5075.164946,2,61,NaN,6.3750
13585,12570,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,5181.311509,6205.829154,11325.017623,2,40,NaN,NaN
13586,12570,2,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,5181.311509,6205.829154,11325.017623,2,40,NaN,NaN
13587,12570,3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,5181.311509,6205.829154,11325.017623,2,40,NaN,NaN
13588,12571,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,6.1875
13589,12571,2,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,NaN
13590,12571,3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,NaN
13591,12571,4,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,7.5000
13592,12571,5,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,7.5000

Print value counts for <tt>birthord</tt> and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611933)

In [10]:
df.birthord.value_counts().sort_index()

1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: birthord, dtype: int64

Print value counts for <tt>prglngth</tt> and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611931)

In [11]:
df.prglngth.value_counts().sort_index()

0       15
1        9
2       78
3      151
4      412
5      181
6      543
7      175
8      409
9      594
10     137
11     202
12     170
13     446
14      29
15      39
16      44
17     253
18      17
19      34
20      18
21      37
22     147
23      12
24      31
25      15
26     117
27       8
28      38
29      23
30     198
31      29
32     122
33      50
34      60
35     357
36     329
37     457
38     609
39    4744
40    1120
41     591
42     328
43     148
44      46
45      10
46       1
47       1
48       7
50       2
Name: prglngth, dtype: int64

Print value counts for <tt>agepreg</tt> and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611935).

Looking at this data, please remember my comments in the book about the obligation to approach data with consideration for the context and respect for the respondents.

In [12]:
df.agepreg.value_counts().sort_index()

10.33     1
10.50     1
10.83     1
10.91     1
11.08     1
11.41     1
11.50     1
11.75     2
12.08     1
12.25     1
12.41     2
12.50     1
12.66     2
12.75     1
12.83     2
12.91     1
13.00     2
13.08     1
13.16     1
13.25     4
13.33     1
13.50     3
13.58     2
13.66     5
13.75     4
13.83     5
13.91     5
14.00     5
14.08     7
14.16    12
         ..
40.50     6
40.58     4
40.66     4
40.75     2
40.83     4
40.91     4
41.00     2
41.08     2
41.16     2
41.25     6
41.33     1
41.41     2
41.58     4
41.75     3
41.83     1
41.91     4
42.08     2
42.16     1
42.25     1
42.33     1
42.41     1
42.50     2
42.58     2
42.75     2
43.00     3
43.16     1
43.25     4
43.58     3
43.91     1
44.08     1
Name: agepreg, dtype: int64

Compute the mean birthweight.

In [3]:
df.totalwgt_lb.mean()

7.265628457623368

Create a new column named <tt>totalwgt_kg</tt> that contains birth weight in kilograms.  Compute its mean.  Remember that when you create a new column, you have to use dictionary syntax, not dot notation.

In [13]:
df['totalwgt_kg']=df.totalwgt_lb*0.453592
df.head()

,caseid,pregordr,howpreg_n,howpreg_p,moscurrp,nowprgdk,pregend1,pregend2,nbrnaliv,multbrth,...,religion_i,metro_i,basewgt,adj_mod_basewgt,finalwgt,secu_p,sest,cmintvw,totalwgt_lb,totalwgt_kg
0,1,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,8.8125,3.997279
1,1,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,7.8750,3.572037
2,2,1,NaN,NaN,NaN,NaN,5.0,NaN,3.0,5.0,...,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,9.1250,4.139027
3,2,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,7.0000,3.175144
4,2,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,6.1875,2.806601

Look through the codebook and find a variable, other than the ones mentioned in the book, that you find interesting.  Compute values counts, means, or other statistics.

Create a boolean Series.

In [4]:
df.outcome == 1

0         True
1         True
2         True
3         True
4         True
5         True
6         True
7         True
8         True
9         True
10        True
11        True
12        True
13       False
14       False
15        True
16        True
17        True
18       False
19        True
20        True
21        True
22       False
23        True
24        True
25        True
26        True
27        True
28        True
29        True
         ...
13563     True
13564     True
13565     True
13566     True
13567    False
13568    False
13569     True
13570     True
13571     True
13572     True
13573     True
13574     True
13575    False
13576     True
13577    False
13578     True
13579     True
13580    False
13581     True
13582    False
13583    False
13584     True
13585    False
13586    False
13587    False
13588     True
13589    False
13590    False
13591     True
13592     True
Name: outcome, dtype: bool

Use a boolean Series to select the records for the pregnancies that ended in live birth.

In [5]:
live = df[df.outcome == 1]
len(live)

9148

Count the number of live births with <tt>birthwgt_lb</tt> between 0 and 5 pounds (including both).  The result should be 1125.

In [6]:
len(live[(live.birthwgt_lb >= 0) & (live.birthwgt_lb <= 5)])

1125

Count the number of live births with <tt>birthwgt_lb</tt> between 9 and 95 pounds (including both).  The result should be 798

Use <tt>birthord</tt> to select the records for first babies and others.  How many are there of each?

In [7]:
firsts = df[df.birthord==1]
others = df[df.birthord>1]
len(firsts), len(others)

(4413, 4735)

Compute the mean weight for first babies and others.

In [8]:
firsts.totalwgt_lb.mean()

7.201094430437772

In [9]:
others.totalwgt_lb.mean()

7.325855614973262

Compute the mean <tt>prglngth</tt> for first babies and others.  Compute the difference in means, expressed in hours.

In [15]:
import chap01_ex
df2 = chap01_ex.ReadFemResp()
df2

,caseid,rscrinf,rdormres,rostscrn,rscreenhisp,rscreenrace,age_a,age_r,cmbirth,agescrn,...,pubassis_i,basewgt,adj_mod_basewgt,finalwgt,secu_r,sest,cmintvw,cmlstyr,screentime,intvlngth
0,2298,1,5,5,1,5.0,27,27,902,27,...,0,3247.916977,5123.759559,5556.717241,2,18,1234,1222,18:26:36,110.492667
1,5012,1,5,1,5,5.0,42,42,718,42,...,0,2335.279149,2846.799490,4744.191350,2,18,1233,1221,16:30:59,64.294000
2,11586,1,5,1,5,5.0,43,43,708,43,...,0,2335.279149,2846.799490,4744.191350,2,18,1234,1222,18:19:09,75.149167
3,6794,5,5,4,1,5.0,15,15,1042,15,...,0,3783.152221,5071.464231,5923.977368,2,18,1234,1222,15:54:43,28.642833
4,616,1,5,4,1,5.0,20,20,991,20,...,0,5341.329968,6437.335772,7229.128072,2,18,1233,1221,14:19:44,69.502667
5,845,1,5,4,1,5.0,42,42,727,42,...,0,2335.279149,3725.796795,4705.681352,2,18,1234,1222,17:10:13,95.488000
6,10333,5,5,3,1,5.0,17,17,1029,17,...,0,2335.279149,2687.399758,3139.151658,2,18,1236,1224,14:14:38,61.204333
7,855,5,5,4,5,5.0,22,22,965,22,...,0,4670.558298,7122.614751,10019.382170,2,18,1235,1223,14:42:52,59.756333
8,8656,5,5,4,1,5.0,38,38,780,38,...,0,5198.652195,6027.568848,6520.021223,2,18,1237,1225,15:32:34,56.978833
9,3566,5,5,4,5,5.0,21,21,974,21,...,0,2764.142038,3240.986558,4559.095792,2,18,1231,1219,16:22:25,104.744667
10,5917,1,5,3,1,5.0,44,43,714,43,...,0,2418.624283,2762.143030,3488.586646,2,18,1233,1221,15:38:06,96.850167
11,9200,5,5,3,1,5.0,26,26,923,26,...,0,2418.624283,2754.293339,2987.031126,2,18,1237,1225,14:12:31,61.060667
12,6320,5,5,5,5,1.0,23,23,952,23,...,0,5497.225851,6448.332868,7241.477811,1,18,1236,1224,14:27:20,69.906500
13,11700,1,5,4,1,5.0,34,34,822,34,...,0,3362.448309,3677.062170,4666.559600,1,18,1236,1224,11:35:31,77.493333
14,7354,1,5,4,1,5.0,28,28,896,28,...,0,2417.628123,2790.899197,3026.730179,1,18,1235,1223,14:40:18,79.018500
15,3697,5,5,4,5,5.0,28,28,896,28,...,0,9670.512492,18559.585881,31215.367494,1,18,1236,1224,11:59:26,45.963500
16,4881,1,5,5,1,5.0,23,23,948,23,...,0,3292.089359,3935.302679,4419.344908,1,18,1234,1222,20:37:54,110.416833
17,5862,1,5,4,1,5.0,33,33,831,33,...,0,3056.771190,3456.489520,4386.630850,1,18,1234,1222,16:42:13,107.819667
18,8542,5,5,5,5,5.0,16,16,1036,16,...,0,5900.163872,6697.056170,7822.831313,1,18,1237,1225,13:04:36,72.481500
19,2054,1,5,4,5,1.0,24,24,939,24,...,0,2417.628123,2570.384230,2886.541491,1,18,1236,1224,13:58:43,87.417500
20,3719,5,5,2,5,5.0,22,22,972,22,...,1,4168.324350,4879.253694,5479.401898,1,18,1238,1226,12:50:26,53.782000
21,11740,1,5,5,1,5.0,32,32,843,32,...,0,2417.628123,2790.899197,3541.930171,1,18,1234,1222,14:23:08,92.950500
22,11343,1,5,5,1,5.0,41,41,741,41,...,0,2417.628123,4394.216361,5549.895265,1,18,1237,1225,20:29:06,70.791667
23,7075,1,5,4,1,5.0,37,37,782,37,...,0,4308.038516,5562.306199,6016.746616,2,18,1232,1220,16:30:34,80.659000
24,5422,1,5,2,1,5.0,38,38,773,38,...,0,3363.768618,3948.605534,4271.206606,1,18,1234,1222,17:07:52,45.171500
25,2178,5,5,3,1,5.0,29,29,877,29,...,0,3363.768618,5306.521605,5754.922681,1,18,1234,1222,18:28:12,77.489833
26,8358,5,5,4,5,5.0,21,21,977,21,...,0,2418.624283,2688.131135,3018.771264,2,18,1237,1225,16:10:17,28.934833
27,5083,1,5,4,1,5.0,37,37,789,37,...,0,2418.624283,3119.659072,3374.535218,2,18,1236,1224,15:14:10,58.307000
28,1545,5,5,4,1,5.0,39,39,762,39,...,0,8034.280664,8972.807739,9705.886131,2,18,1237,1225,14:09:31,53.124833
29,5656,5,5,3,5,5.0,26,26,921,26,...,0,4170.041867,6582.846660,7139.097203,2,18,1238,1226,11:20:54,61.501000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7613,4640,5,5,6,5,5.0,18,18,1016,18,...,0,2273.045919,5800.771072,10202.976239,1,76,1234,1222,12:01:09,84.903833
7614,3998,5,5,2,5,5.0,24,24,935,24,...,0,3544.869231,4031.967457,5671.768622,1,76,1228,1216,17:11:53,106.922500
7615,2432,5,5,5,5,5.0,15,15,1048,15,...,0,7576.875171,8452.387480,14866.904339,2,76,1234,1222,16:41:31,40.803333
7616,5438,1,5,3,5,5.0,30,30,862,30,...,0,2273.062551,2559.633775,4440.964600,2,76,1229,1217,12:50:02,86.785000
7617,9643,1,5,2,5,5.0,24,24,929,24,...,0,2597.785773,2969.368501,4177.010670,2,76,1229,1217,12:26:15,89.036000
7618,3030,1,5,1,5,5.0,34,34,811,34,...,0,2273.062551,2525.629369,4381.966956,2,76,1229,1217,14:23:39,80.175667
7619,11585,1,5,4,5,5.0,34,34,814,34,...,0,1720.605492,2260.899193,3922.660100,1,76,1228,1216,15:59:28,113.677500
7620,6677,1,5,4,1,5.0,26,26,909,26,...,0,3613.271533,4035.558807,4376.563526,1,76,1227,1215,16:35:57,110.918333
7621,10744,5,5,8,5,1.0,22,22,968,22,...,0,3082.751506,3278.300013,4611.584628,1,76,1234,1222,14:08:25,95.713167
7622,8403,5,5,4,5,5.0,19,19,995,19,...,0,2408.847688,2563.254954,4508.509139,1,76,1228,1216,17:36:32,62.217000
7623,7574,5,5,4,5,5.0,19,19,997,19,...,0,2272.098197,2482.173894,4365.895661,2,76,1228,1216,16:09:34,96.809833
7624,8000,1,5,5,5,5.0,37,37,780,37,...,0,4544.196393,4924.699453,8987.084031,2,76,1227,1215,16:40:18,140.088333
7625,6288,5,1,3,5,2.0,20,20,986,20,...,0,2272.098197,2585.825443,3637.480651,2,76,1227,1215,17:40:15,93.622333
7626,5856,5,5,6,5,3.0,23,23,958,23,...,0,12456.163382,31787.898176,44716.036364,1,76,1238,1226,16:04:09,69.623500
7627,8794,1,5,3,5,5.0,23,23,945,23,...,0,6818.699775,7950.887074,11184.512847,1,76,1228,1216,18:23:51,77.508000
7628,6365,5,5,3,5,2.0,17,17,1028,17,...,0,2272.899925,3456.977988,6080.478584,1,76,1235,1223,17:15:36,46.016667
7629,3537,1,5,3,5,2.0,36,36,797,36,...,0,3918.792974,5258.971089,9597.096340,1,76,1239,1227,15:19:09,85.378000
7630,1515,1,5,1,5,5.0,44,44,688,44,...,0,2272.899925,2680.745920,4467.463075,1,76,1228,1216,16:23:34,147.769667
7631,9174,1,5,3,5,3.0,32,32,834,32,...,0,2272.899925,2608.931475,4526.496109,1,76,1228,1216,17:30:08,171.005000
7632,4213,1,5,3,5,2.0,40,40,748,40,...,0,2272.948899,2659.474205,4432.013762,2,76,1229,1217,09:47:43,99.248667
7633,6804,5,5,3,5,2.0,35,35,805,35,...,0,3247.069856,3814.222882,6960.575338,2,76,1229,1217,14:20:39,103.929167
7634,1282,1,5,4,5,3.0,35,35,798,35,...,0,2068.394620,2222.154405,4055.209574,1,76,1228,1216,16:31:47,105.509000
7635,2954,1,5,4,5,3.0,30,30,862,30,...,0,2068.394620,2356.019463,4087.693768,1,76,1228,1216,19:40:51,85.290167
7636,4964,1,5,3,5,3.0,41,41,727,41,...,0,2068.394620,2222.154405,3703.220316,1,76,1227,1215,12:38:19,306.238000
7637,143,1,5,1,5,2.0,35,35,808,35,...,0,2273.211779,2463.724427,4496.050707,2,76,1230,1218,17:45:36,83.798833
7638,11018,1,5,2,5,3.0,34,34,811,34,...,0,3247.445399,3784.333145,6565.818007,2,76,1228,1216,15:57:38,82.907333
7639,6075,5,5,3,5,3.0,17,17,1014,17,...,0,2273.211779,2497.234491,4392.385746,2,76,1228,1216,18:23:53,54.044833
7640,5649,1,5,2,5,5.0,29,29,873,29,...,0,3247.445399,3569.313710,6003.228729,2,76,1228,1216,18:42:41,68.168000
7641,501,5,5,3,5,2.0,16,16,1034,16,...,0,5304.160818,5954.644352,10473.623950,2,76,1228,1216,16:02:45,32.717333
7642,10252,1,5,2,5,2.0,28,28,889,28,...,0,3247.445399,3476.637428,5847.356491,2,76,1230,1218,12:45:19,74.061500